[package]
name = "dog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
chia = "0.15.0"
chia-wallet-sdk = "0.19.1"
clvmr = "0.9.0"
hex = "0.4.3"
hex-literal = "0.4.1"
rstest = "0.23.0"
